pipeline {
    agent any

    parameters {
        string(name: 'TARGET_HOST', defaultValue: '', description: 'IP address of the EC2 instance to deploy to')
    }

    environment {
        REPO_URL   = 'https://github.com/abeerseada/sdn'
        REPO_DIR   = '/opt/sdn'
        SSH_CREDS  = 'ec2-ssh-key'        
        SSH_USER   = 'ubuntu'
    }

    stages {

        stage('Run Pipeline') {
            steps {
                script {
                    load('Jenkins/stages/validate_parameters.groovy').call()
                    load('Jenkins/stages/clone_repo.groovy').call()
                    load('Jenkins/stages/reset_deployment.groovy').call()
                    load('Jenkins/stages/deploy_topology.groovy').call()
                    load('Jenkins/stages/configure_switches.groovy').call()
                    load('Jenkins/stages/verify_deployment.groovy').call()
                }
            }
        }
    }

    post {
        success {
            echo "SDN topology deployed successfully on ${params.TARGET_HOST}"
            echo "Ryu FlowManager UI available at: http://${params.TARGET_HOST}:8080"
        }
        failure {
            echo "Deployment failed. Check logs above for details."
        }
    }
}
