pipeline {
    agent any

    environment {
        REPO_URL   = 'https://github.com/abeerseada/sdn'
        REPO_DIR   = '/opt/sdn'
        SSH_CREDS  = 'ec2-ssh-key'
        SSH_USER   = 'ubuntu'
        TARGET_HOST = '3.125.116.75'
    }

    stages {

        stage('Run Pipeline') {
            steps {
                script {
                    load('Jenkins/stages/validate_parameters.groovy').call()
                    load('Jenkins/stages/clone_repo.groovy').call()
                    load('Jenkins/stages/reset_deployment.groovy').call()
                    load('Jenkins/stages/setup_dc.groovy').call()
                    load('Jenkins/stages/deploy_topology.groovy').call()
                    load('Jenkins/stages/configure_switches.groovy').call()
                    load('Jenkins/stages/verify_deployment.groovy').call()
                }
            }
        }
    }

    post {
        success {
            echo "SDN topology deployed successfully on ${env.TARGET_HOST}"
            echo "Ryu FlowManager UI available at: http://${env.TARGET_HOST}:8081"
        }
        failure {
            echo "Deployment failed. Check logs above for details."
        }
    }
}
